iij/mruby-io

src/io.c
Fix for #37 caused a compilation error on Windows (pid_t isn't defined). Since none of the process functions are implemented on windows, I've just wrapped the waitpid call in an #if.
=> Excluding wait call for windows

mrblib/file_constants.rb, src/file.c
Just noticed File::NULL was always set to /dev/null. Should be 'NUL' on Windows.
=> Correct File::NULL for Windows

src/io.c
Uncovered with a Coverity scan of our project using mruby-io. https://scan8.coverity.com/reports.htm#v26153/p11375/fileInstanceId=6844382&defectInstanceId=2515905&mergedDefectId=121921
=> Remove mrb_io_s_select typo.

mrbgem.rake
This fixes #17. We're doing cross compiling on Linux to Windows for [mruby-cli](https://github.com/hone/mruby-cli).
=> support for crossbuild for windows (32 bit and 64 bit) using mingw

src/file.c
Provide a `File::PATH_SEPARATOR` for *nix and windows.
=> define PATH_SEPARATOR

run_test.rb
`ruby run_test.rb all test` seems not to execute test without this patch.
=> enable test

src/io.c
When file-size is too big like 3GiB, `io.seek(0, IO::SEEK_END) ` got sysseek error by buffer overflow of `pos` even if `MRB_INT64` is enabled.
=> Fix buffer overflow of `pos` when file-size is too big

README.md, mrblib/io.rb, src/io.c, test/io.rb
I propose `IO.pipe` like as CRuby.
But encode option was nothing.
And defined internal method `IO._pipe` same as with none block call `IO.pipe`.
Because this is difficult that embed `ensure` in mruby C-API.
=> Implement IO.pipe

src/io.c, test/mruby_io_test.c
I tried to build on Win32 environment with AppVeyor CI.
With this fix (and appveyor.yml file on https://github.com/takahashim/mruby-io/commit/8238cf9f57fb4e9cec919ce83d2c12e844fcaf5f ), I made build pass on AppVeyor.
(But some tests are failded and need to fix.)
https://ci.appveyor.com/project/takahashim/mruby-io/build/%2327
I'm not sure support policy of mruby-io on Windows, so this PR might not be useful (especially handling `test/mruby_io_test.c`).   But mruby-io has already had some `_WIN32` conditions, so this PR might not be so bad, I hope.
=> build on Win32

test/mruby_io_test.c
Without "b", `fputs()` in Windows uses CRLF as `\n`, not LF.
=> fix tests for Win: use binary mode

src/file.c
* `File::SEPARATOR` should be `"/"`
* `File::ALT_SEPARATOR` should be `"\\"` or `nil`.
cf. http://docs.ruby-lang.org/ja/2.2.0/class/File.html#C_-A-L-T_-S-E-P-A-R-A-T-O-R
=> fix file separator

mrblib/file.rb, mrblib/io.rb, src/file.c, src/file_test.c, test/file.rb, test/file_test.rb, test/io.rb
This PR makes build success on Windows.
* `File.expand_path`: support drive letter and `ALT_SEPARATOR`
* `File.dirname`: support `ALT_SEPARATOR`
* `File.basename`: ditto.
* `IO.popen`: raise `NotImplementedError`
* `IO.pipe`: ditto.
* `` `cmd` ``:  ditto.
* `File#flock`: ditto.
* `FileTest.pipe?`: ditto.
* `FileTest.symlink?`: ditto.
* `FileTest.socket?`: ditto.
=> Fix for windows(mingw)

test/mruby_io_test.c
On some platforms the mruby-io tests fail because socket binding fails with `EPERM`.  This occurs because these platforms do not allow a UNIX socket to be created in an arbitrary directory.
To resolve this the socket is created in `/tmp/` instead of the current directory.
=> Test io setup failure

mrblib/io.rb
I wrote [mruby-stringio](https://github.com/ksss/mruby-stringio).
But now, We have to overwrite CONST value for get string of wrote by stdout.
```rb
orig = STDOUT
io = StringIO.new
STDOUT = io
puts "hello"
STDOUT = orig
p io.string #=> "hello\n"
```
I expect to use globel variable like this.
```rb
orig = $stdout
io = StringIO.new
$stdout = io
puts "hello"
$stdout = orig
p io.string #=> "hello\n"
```
=> Should use global variable

mrblib/io.rb, src/io.c, test/io.rb
I implement part of option for IO.popen.
It will be able to get stdout string and stderr string at the same time.
```rb
p IO.pipe{|r,w| [IO.popen("cp", "r", err: w) { |i| i.read }, (w.close; r.read)]}
#=> ["", "usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file\n       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory\n"]
```
=> Enable option :in, :out, :err to IO.popen

src/io.c
Hello. With recent mruby, I had this error:
```
wrong argument type Module (expected Class)
```
when closing a pipe (line 40 in io.rb). I tracked this down to line 81 in io.c. In io_set_process_status, there is this line:
```c
c_process = mrb_class_get(mrb, "Process");
```
In the current code from the mruby-process gem, Process is a module, not a class. I thus needed to change this last line to
```c
c_process = mrb_module_get(mrb, "Process");
```
This solves my problem. I *presume* that this is the appropriate fix. 
Carlo
=> Apparently, in mruby-process gem, Process is now a Module, not a Class

src/io.c
=> Add explicit cast from void* to struct mrb_io*

src/file.c
Fix compile errors when conf.enable_cxx_abi is enabled.
=> Add pointer casting

src/io.c, test/io.rb
- IO#sysread with 0 always return empty string
- IO#sysread should raise IOError when closed
- IO#sysread should raise error when invalid pos
=> Fix some spec for IO#sysread

src/io.c, test/io.rb
Actual
```
$ mruby -e 'IO.pipe { |r,w| w.sysread(1) }'
-e:1:sysread failed (RuntimeError)
$ mruby -e 'IO.pipe { |r,w| r.syswrite("") }'
-e:1:not opened for writing (IOError)
```
Expect
```
$ ruby -e 'IO.pipe { |r,w| w.sysread(1) }'
-e:1:in `sysread': not opened for reading (IOError)
$ ruby -e 'IO.pipe { |r,w| r.syswrite("") }'
-e:1:in `syswrite': not opened for writing (IOError)
```
=> IO#sysread Check for readable

mrblib/io.rb, src/io.c
pos shouldn't cache because it's not controllable.
For example, It's unexpected behavior.
```rb
File.open("tempfile", "w") do |f|
f.syswrite("abc")
f.pos #=> Expect 3, got 0
end
```
Not only that, Another case...
```rb
File.open("tempfile", "w") do |f|
write_method(f.fileno) # write_method use system call write(2) from fd
f.pos #=> ?
end
```
And CRuby's `IO#pos` doesn't use cache value.
https://github.com/ruby/ruby/blob/5aff6f294821574e54f458d547cf9641dd2eca98/io.c#L1629
So, I propose this patch.
=> To accurate `pos`

mrblib/io.rb, test/io.rb
This patch fix the following bugs.
```rb
io = IO.open(IO.sysopen($mrbtest_io_wfname, "r+"), "r+")
io.write("abcdefg")
io.rewind
io.read(2)
io.write("123")
io.rewind
io.read #=> Expect "ab123fg", got "abcdefg123"
io.close
```
=> Reseek when write

mrblib/io.rb
```rb
File.open("foo.md") do |f|
buf = "Hello, "
res = f.read(nil, buf)
p buf #=> "World!"
p res.object_id == buf.object_id #=> true
p f.read(1, buf) #=> nil
p buf #=> ""
end
```
See also https://docs.ruby-lang.org/en/2.4.0/IO.html#method-i-read
=> Support outbuf argument for IO#read

mrblib/io.rb, test/io.rb
Fixes #87. The error was caused by not reducing the number of bytes to read from the internal buffer for consecutive iterations of the `while 1` loop inside `IO#read`.
=> Fix for IO#read(n) with n > IO::BUF_SIZE

src/io.c, test/io.rb
Hi!
Since the new shared strings [have been introduced](https://github.com/mruby/mruby/commit/7edbe428caca6814841195a3f2720745cf04353e), the test below has been failing:
```ruby
assert('IO.sysopen, IO#sysread') do
fd = IO.sysopen $mrbtest_io_rfname
io = IO.new fd
str1 = "     "
str2 = io.sysread(5, str1)
assert_equal $mrbtest_io_msg[0,5], str1
assert_equal $mrbtest_io_msg[0,5], str2
...
end
```
The commit provides a fix (we should explicitly call `mrb_str_modify` if we're going to modify the string).
And also I've added a test for frozen strings.
=> Handle shared/frozen strings in IO#sysread

src/file.c
Only on Windows does MRI try to rename the file with altered file attributes in case the first attempt to `rename` fails.
This PR makes the behavior of mruby-io consitent to that behavior.
The bonus here is that the change eliminates the chance of the named file disappearing from the directory (which, in the current code, happens in the brief moment between calls to `UNLINK` and `rename`).
=> make `rename` behavior consistent with MRI
